### ISSUE TITLE
Scripts do not work on Firefox

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#107]
测试环境：
Firefox 54
Violentmonkey 2.6.3

简称：
GM：Greasymonkey
TM：Tampermonkey
VM：Violentmonkey

- [ ] [斗鱼HTML5播放器](https://greasyfork.org/zh-CN/scripts/26901)
（该脚本本身就不支持Chrome；兼容GM，不兼容TM，不兼容VM）
- [ ] CSP导致Firefox下失效的脚本
（兼容GM，兼容TM，兼容Chrome版VM，不兼容Firefox版VM）
  Firefox下CSP对扩展注入的脚本行为限制与Chrome不一致导致某些脚本不能执行
  - [x] [Github.com - Extra header links](https://greasyfork.org/zh-CN/scripts/3139)
  - [x] [知乎 - 阅读样式 | Userstyles.org](https://userstyles.org/styles/97644/theme)
  - [x] [iZhihu](https://greasyfork.org/zh-CN/scripts/350-izhihu "iZhihu")
  - [x] [Twitter Modal Full Width | Userstyles.org](https://userstyles.org/styles/135922/twitter-modal-full-width)
  - [ ] [Twitter Original Image](https://greasyfork.org/zh-CN/scripts/25348-twitter-original-image "Twitter Original Image")

**Comment by ivysrono** [comment]
[浦发银行个人网银动态密码版 Windows 登录免安全控件](https://greasyfork.org/zh-CN/scripts/7537-%E6%B5%A6%E5%8F%91%E9%93%B6%E8%A1%8C%E4%B8%AA%E4%BA%BA%E7%BD%91%E9%93%B6%E5%8A%A8%E6%80%81%E5%AF%86%E7%A0%81%E7%89%88-windows-%E7%99%BB%E5%BD%95%E5%85%8D%E5%AE%89%E5%85%A8%E6%8E%A7%E4%BB%B6)
GM 支持。
是否是 run-at document-start 具体执行的时间点有差别？

**Comment by ivysrono** [comment]
[浦发银行个人网银动态密码版 Windows 登录免安全控件](https://greasyfork.org/zh-CN/scripts/7537-%E6%B5%A6%E5%8F%91%E9%93%B6%E8%A1%8C%E4%B8%AA%E4%BA%BA%E7%BD%91%E9%93%B6%E5%8A%A8%E6%80%81%E5%AF%86%E7%A0%81%E7%89%88-windows-%E7%99%BB%E5%BD%95%E5%85%8D%E5%AE%89%E5%85%A8%E6%8E%A7%E4%BB%B6)
GM 支持, TM 4.3.5447+ 支持。
是否是 run-at document-start 具体执行的时间点有差别？ 
记得原来在 Chrome 版 VM 是支持的，但现在 2.6.4 和 2.6.3 无论 Chrome/Firefox 都不支持。

**Comment by ivysrono** [comment]
@gera2ld 无意中发现了个奇葩解决方案：
装上 TM，啥也不用动，VM 中的这两个脚本就能正常工作了……
#131 不能这么解

**Comment by ivysrono** [comment]
又来一个
[Twitter Modal Full Width | Userstyles.org](https://userstyles.org/styles/135922/twitter-modal-full-width)
（用脚本模式安装样式，兼容GM，兼容TM，兼容Chrome版VM，不兼容Firefox版VM）

**Comment by gera2ld** [comment]
CSP的是一类，所有此类网站都受影响，包括github.com、twitter.com……不用重复报了。。

**Comment by luxoflux** [comment]
Any solution to this?

**Comment by ivysrono** [comment]
@luxoflux 
1. Tampermonkey
2. security.csp.enable;false

**Comment by luxoflux** [comment]
I found this setting:

![csp - copy](https://user-images.githubusercontent.com/9421932/27472428-1f199492-57b0-11e7-8228-da2167a13271.png)

Maybe Violentmonkey can do something similar.

**Comment by gera2ld** [comment]
@luxoflux This should be the final solution but not implemented yet.

**Comment by xcffl** [comment]
[Steam Prices](https://github.com/FirefoxBar/userscript/tree/master/Steam_Prices)
看起来与CSP无关？

**Comment by jspenguin2017** [comment]
Since script injected from content script are not affected by CSP, maybe expose a special `eval` (maybe `VM_eval`?) that goes through the content page? 
So basically send the code to content page, then the content page inject it back. The problem is that it is asynchronous, it's really just a single tick as it is the same process, but it will be different than the real `eval`.

**Comment by gera2ld** [comment]
It's impossible for Firefox to send the code to content page, because the initialization code cannot even be injected into the web page at the beginning.
`unsafe-eval` should not be used as well as `eval` anywhere else.
I think it is acceptable to add `nonce` for specific code to be injected.

**Comment by jspenguin2017** [comment]
So you are worried that webpages may be able to tamper `CustomEvent` or `dispatchEvent`? But what about `GM_xmlHttpRequest`? You got to have some way to communicate back to content script...

**Comment by gera2ld** [comment]
It's not about communicating back. In Firefox without CSP modified, you can not even inject into web page, so there is no communicating back. Communicating back is never a problem, the problem is that we cannot inject into the web page.

**Comment by jspenguin2017** [comment]
Wait, that's not right, the standard says extensions are excluded from CSP, it sounds like a bug in Firefox.

**Comment by gera2ld** [comment]
That's why this issue only occurs on Firefox.

**Comment by ivysrono** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/418
不知有无参考价值。

**Comment by nazar-pc** [comment]
Here is one more user script suffering from this issue: https://github.com/StylishThemes/GitHub-Dark-Script/issues/13
I was forced to move to Violentmonkey since Firefox Nightly 57 broke Greasemonkey.

**Comment by jspenguin2017** [comment]
I think basically we have to edit the headers to change CSP, that would create so many conflicts with other extensions, as headers event is asynchronous and only the extension that is installed last can reliably override the headers.

**Comment by nazar-pc** [comment]
I believe this is much better than nothing. Extensions will rarely override headers.
Is there any upstream Firefox issue about this?

**Comment by jspenguin2017** [comment]
Firefox CSP is broken for a long time, I think they don't want to change it, which is kind of weird as some extensions will change it in an irresponsible way.

**Comment by BoBeR182** [comment]
Seems to be related to https://github.com/violentmonkey/violentmonkey/issues/252

**Comment by ivysrono** [comment]
@BoBeR182 No, just about CSP.
Fixed in 58+

**Comment by nille02** [comment]
Sure that's fixed in FF? I use FF59 (VM2.9.1) and had to set security.csp.enable;false or my scripts are not running :/

**Comment by BoBeR182** [comment]
It seem's to have regressed in FF59+ please reopen.

**Comment by luxoflux** [comment]
Confirming it's still an issue. Doesn't work on sites like `twitter.com` and `tweetdeck.twitter.com`.

**Comment by woyaojizhu8** [comment]
Confirming it's still an issue. Doesn't work on sites like zhihu.com.

**Comment by DRSAgile** [comment]
The scripts still can be run with CSP-enable sites if "auto" injection mode is selected in the VM setting.

The issue is, there are limitations of what "content" injection can offer which can not be solved by ViolentMonkey.

You can get to "page" side by overtly creating a script element and putting part of your JS code there. However, that part of your code will not be able to grant permissions such GM_openInTab.
