### ISSUE TITLE
OUJS Update Issue

### ISSUE THREAD

**Issue by projecthate** [violentmonkey/violentmonkey#1622]
Hello, for some time I've been experiencing an issue with updating scripts through OUJS. An admin there is pretty confident it is a VM issue and encouraged me to post here to have you look into it. Our discussion is here: https://openuserjs.org/discuss/Scripts_not_properly_installing

**Comment by tophf** [comment]
Judging by [the comment](https://openuserjs.org/discuss/Scripts_not_properly_installing#comment-183e72fa206) it's a bug I added in 2.13.2. Let me fix it...

**Comment by tophf** [comment]
No, closing of the topic indicates the source code is fixed. AFAIK this is how most bug trackers work.

**Comment by projecthate** [comment]
Okay so it's fixed but I'm still encountering the issue? What does that
mean?

Fixed should = issue resolved, no?

**Comment by tophf** [comment]
> the source code is fixed

**Comment by tophf** [comment]
Until the next version is released you'll have to disable the update check for scripts from OUJS. If the script was already truncated by the update, please reinstall it on OUJS without removing.

**Comment by projecthate** [comment]
Thanks for the clarification @tophf - do you have any insights on when the revision will be released?

**Comment by tophf** [comment]
Soon, I guess. FWIW, a fixed beta is already released.
