### ISSUE TITLE
[Feature] Option to skip/disable recycle bin

### ISSUE THREAD

**Issue by mikelei8291** [violentmonkey/violentmonkey#1710]
**Motivation**

It's nice to have a chance to undo the deletion, but for me who believe in yolo, I'd like to delete the script permanently when I delete it.

**Proposed Solution**

Add an option in the settings page to disable the recycle bin, so that when deleting scripts they would be removed permanently.

**Use Cases**

Enable the option and yolo.

**Comment by mikelei8291** [comment]
That's a good idea. However, I do think it would be great if we can have all the options placed in one place so we know where to find them. Also, if the value is `0` why not just hide the recycle bin tab (as in the latest BETA version) completely?

**Comment by tophf** [comment]
Normally it's easier to find a contextually placed option than wade through a forest of options and switch back and forth to see the effect of toggling it, moreover it'll be shown instead of the current notice about the 7 days grace period.

If the label irritates you you can hide it using custom CSS in settings:

```css
[href="#recycleBin"] {
  display: none !important;
}
```

**Comment by gera2ld** [comment]
Closing since the issue is resolved.
As for improvements on UI please refer to #1714

**Comment by mikelei8291** [comment]
@gera2ld Wait, this issue is not resolved as the feature is not implemented yet. The feature was not just hiding the recycle bin tab in the UI, but to disable the function of it so when the user deletes a userscript it will be removed permanently.
