### ISSUE TITLE
[BUG] When refreshing or creating a new page, there is a chance that ViolentMonkey will not load the script.

### ISSUE THREAD

**Issue by kidzgy** [violentmonkey/violentmonkey#1739]
- [ TRUE ] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [ TRUE ] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
When refreshing or creating a new page, there is a chance that ViolentMonkey will not load the script.

**To Reproduce**
Note that issues without a reproduction may be closed immediately!
It's random.

**Expected behavior**

**Actual behavior**
As you can see in the image below, the name of the enabled script is colored gray, meaning that the script is enabled but not loaded.When I returned the extension to version 2.13.3, the problem was not present.
![微信截图_20230201095727](https://user-images.githubusercontent.com/6967810/215926559-65794d1e-4998-4107-b4a0-382d1462df03.png)

**Environment:**
- OS: Win10 x64
- Browser: Firefox
- Browser Version: 
108
- Violentmonkey Version:2.13.9

**Additional context**

**Comment by klcb2010** [comment]
你灰色脚本看起来没有启用呀  刷新一次他会自动关闭？

**Comment by kidzgy** [comment]
> 你灰色脚本看起来没有启用呀 刷新一次他会自动关闭？

看最左边的开启/关闭的圆点，脚本是启用了，只是没被加载。重新再刷新一下页面的话，脚本会被加载。

我现在换109版本试用几天再反馈。

**Comment by kidzgy** [comment]
![微信截图_20230202221145](https://user-images.githubusercontent.com/6967810/216347781-073a7656-7f50-4c8c-b956-709c70fc4f9f.png)
用最新的扩展和FF109测试了一下，还是存在这样的问题。
如果要复现，可以尝试一次性加载10多个标签（比如书签文件夹一次打开），这样复现的概率大很多。

**Comment by tophf** [comment]
I couldn't reproduce it. Maybe you can find the [latest beta](https://github.com/violentmonkey/violentmonkey/releases) that works for you? Also, are the errors in devtools console for the tab and for the extension in `about:debugging`?

![image](https://user-images.githubusercontent.com/1310400/216351742-4092056f-18a5-4b87-b104-b7ea5fea215f.png)

**Comment by kidzgy** [comment]
> I couldn't reproduce it. Maybe you can find the [latest beta](https://github.com/violentmonkey/violentmonkey/releases) that works for you? Also, are the errors in devtools console for the tab and for the extension in `about:debugging`?
> 
> ![image](https://user-images.githubusercontent.com/1310400/216351742-4092056f-18a5-4b87-b104-b7ea5fea215f.png)

我使用的就是[BETA v2.13.9.1](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.9.1)这个版本，也还是会出现这样的问题。
而且很神奇的是，一次性打开多个标签，假设一个网站没有成功加载到脚本，那么同一批的其他所有网站同样加载脚本失败。

**Comment by tophf** [comment]
No, I'm asking you to find which beta version added this bug.

**Comment by kidzgy** [comment]
Okay I understand, but it will take some time, I guess there are not so fast results.

**Comment by klcb2010** [comment]
今天复现了你的问题109.0.1  ， 暴力猴2.13.9  ，脚本是开启的  但是没生效 ， 显示灰色
![截屏图片](https://user-images.githubusercontent.com/32628414/216815560-a0b9b4c3-67d5-4167-9bf9-eed2b6a45512.jpg)

**Comment by kidzgy** [comment]
我发现2.13.4开始之后就有这种情况了，2.13.3是还没有的，所以我现在在测试2.13.3 至2.13.4的beta版本

**Comment by kidzgy** [comment]
The last normal version I found was 2.13.3.7, and I've had this problem since 2.13.3.8.
![Uploading 微信截图_20230207235945.png…]()

**Comment by tophf** [comment]
The most suspicious change in [this range](https://github.com/violentmonkey/violentmonkey/compare/v2.13.3.7...v2.13.3.8) is switching from `global` to `self` when setting `vmData` which contains the scripts. I'll revert it.

**Comment by kidzgy** [comment]
If possible, can I have a separate version for further testing?

**Comment by kidzgy** [comment]
I found that whenever the script could not be loaded successfully, the following error appears in the console.
![微信截图_20230208020523](https://user-images.githubusercontent.com/6967810/217329260-67f508f9-706f-4b3f-90dc-3e38d4811aa9.png)

**Comment by kidzgy** [comment]
![微信截图_20230208092044](https://user-images.githubusercontent.com/6967810/217404210-55e311d2-d32a-4057-946b-a3471f99161c.png)
There is no any infomation.

**Comment by kidzgy** [comment]
> Test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/10836140204/artifacts/545745450).
> 
> As for the error, try clicking the link at the right, which should open the source code, then press `{}` button: ![image](https://user-images.githubusercontent.com/1310400/217332083-8e234194-575b-429a-bc9f-6de516f8b83f.png)

Tried this version and still have the same problem.
![微信截图_20230208141755](https://user-images.githubusercontent.com/6967810/217450336-1da58c9a-1fc4-46b0-850e-7c3aa1b0cfd2.png)

**Comment by tophf** [comment]
Try [this build](https://github.com/violentmonkey/violentmonkey/suites/10836781882/artifacts/545793783) and disable "Alternative page mode in Firefox":

![image](https://user-images.githubusercontent.com/1310400/217453198-d287f3b1-f0ca-444c-ab46-2b4ddc31ce40.png)

**Comment by kidzgy** [comment]
> Try [this build](https://github.com/violentmonkey/violentmonkey/suites/10836781882/artifacts/545793783) and disable "Alternative page mode in Firefox":
> 
> ![image](https://user-images.githubusercontent.com/1310400/217453198-d287f3b1-f0ca-444c-ab46-2b4ddc31ce40.png)

Still have the same problem.

**Comment by tophf** [comment]
1. What is your "Default injection mode"?
2. Does the problem happen on all sites or just some sites? Example URL please.

**Comment by kidzgy** [comment]
> 1. What is your "Default injection mode"?
> 
>     2. Does the problem happen on all sites or just some sites? Example URL please.

1. "Default injection mode" is "Auto"
![微信截图_20230208160718](https://user-images.githubusercontent.com/6967810/217472338-2de8a12c-d9ec-466c-9536-db5b6f2b5d45.png)

2.The sites that have problems are random and not site specific.
① When there is a list of scripts but the script is not loaded, the console error is "Error: k[1] is undefined".
② When the script list is empty (i.e. all information about the script is not read, including the script name), the console error is "Error: p is undefined".
The above error appears in the console without any more detailed information.
The sites I have tested for the above ① phenomenon are "www.vrmoo.cn", "www.h3wog.com" and "www.ablesci.com ".
I have tested the above-mentioned (ii) websites: "www.2cycd.com", "www.ppxclub.com", "www.yysub.net ".
![微信截图_20230208162115](https://user-images.githubusercontent.com/6967810/217474718-487bc652-df4e-4826-9db9-1505b765474d.png)
![微信截图_20230208161354](https://user-images.githubusercontent.com/6967810/217474730-6f868c9a-79ae-4176-b4d8-2b1a5e2f2227.png)
![微信截图_20230208161208](https://user-images.githubusercontent.com/6967810/217474759-d90e90ae-c30c-4a1a-97c2-f062987e217e.png)


The way I specifically reproduce the operation is as follows.
(1) Close your browser, re-run your browser and wait about 10 seconds to make sure all extensions have loaded.
(2) Open 10+ tabs at the same time (you can bookmark 10+ websites in advance so that you can right click to open them all at once).
(3) Wait for all websites to load.
(4) Check each open tab to see if the Violent Monkey loading script is working properly.

**Comment by kidzgy** [comment]
It may not always be possible to reproduce the problem successfully. If the reproduction fails, restart the browser and try the whole process all over again.

**Comment by tophf** [comment]
I can't reproduce the problem using this instruction after 10 attempts. Maybe it's caused by some of the scripts that you have. Try disabling all of them and re-enable until it starts failing.

**Comment by kidzgy** [comment]
You can try this version of Firefox, I just tried to reproduce the problem.
https://www.lanzoui.com/b851982  password：4t8p

**Comment by kidzgy** [comment]
I've tried disabling and re-enabling them all, and it didn't work.
I now have to go back to version 2.13.3.

**Comment by kidzgy** [comment]
This is my own Firefox downloaded from the official, patched with portable, already installed VM, and imported my own commonly used scripts, in addition I will test the bookmarks also placed in the toolbar, the folder named "Test", just open Firefox, then right-click on the folder and open all the bookmarks at the same time. The problem can be reproduced.
If you can't reproduce the problem, please close all the tabs and restart the browser, then test again, and so on. I was able to reproduce the problem after testing.

The download link is: https://wwi.lanzoup.com/icy0D0n0bk7c
Please download "FirefoxPortable.rar" and unzip it.

**Comment by tophf** [comment]
I see it now immediately on the first try, thanks. I'll investigate.

**Comment by tophf** [comment]
So it was pure luck that I encountered the bug as it occurs only if I click Violentmonkey icon in the toolbar while the other tabs were loading. Anyway, now it should be fixed. Test build: [link](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml?query=branch%3Amaster).

The reason was a bug in Firefox: it sends messages without `tab` object from some iframes, probably when the iframe was removed right after sending a message. All iframes were advertisements by doubleclick.net. Most Firefox users didn't encounter this problem because they don't open Violentmonkey while opening a several tabs simultaneously and they use adblockers.

**Comment by fullmetal1** [comment]
That's strange, I've had this same issue even when I open a single tab and I have ublock installed.

I'd like to test your test build but when I go to the page and find and download the 'artifact' it just gives me a .zip that doesn't install if I rename it to a .xpi (I am probably just missing the actual download)

**Comment by tophf** [comment]
Zip files are installed on `about:debugging` page in Firefox. You may need to unpack it first.

**Comment by tophf** [comment]
Actually a beta is already released so you can take the xpi there.

**Comment by kidzgy** [comment]
![微信截图_20230210140641](https://user-images.githubusercontent.com/6967810/218015778-6ebc0935-514b-4b9f-8275-27140af9f715.png)
I tried version 2.13.9.2 and still have the same problem.

**Comment by tophf** [comment]
I don't have any new ideas. I can't reproduce the problem anymore. Hopefully someone else will be able to debug it.

**Comment by tophf** [comment]
I actually have an idea, there was a place I missed where Firefox bug could break our code, here's the test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/10897508540/artifacts/550340422).

**Comment by kidzgy** [comment]
> I actually have an idea, there was a place I missed where Firefox bug could break our code, here's the test build: [zip](https://github.com/violentmonkey/violentmonkey/suites/10897508540/artifacts/550340422).

I tried this version and still have the same problem.

**Comment by tophf** [comment]
Are there any errors in console?

**Comment by kidzgy** [comment]
It seems to be normal. I just installed the new version, I may have forgotten to close and restart the browser, resulting in the test results are still not in effect. Sorry!
I need to test for 1-2 more days to make sure the effect is perfect.

**Comment by tophf** [comment]
Don't forget that when you restart he browser the `zip` extension is automatically replaced with your previous version of the extension, which resides in an `xpi` file inside the browser profile.

**Comment by kidzgy** [comment]
Now I'm pretty sure that the latest version of zip still has the same problem, with the following error code.
![微信截图_20230210154431](https://user-images.githubusercontent.com/6967810/218032451-ea20162a-6a81-4381-a6cf-39bb6c1947f6.png)

**Comment by tophf** [comment]
Try this build: [zip](https://github.com/violentmonkey/violentmonkey/suites/10907866610/artifacts/551052376)

**Comment by kidzgy** [comment]
![微信截图_20230211014135](https://user-images.githubusercontent.com/6967810/218159820-ba43609d-b762-46a0-8fa3-4ec08a244158.png)
Still.

**Comment by tophf** [comment]
Could you please share your backup of Violentmonkey scripts again? Maybe it'll help me replicate the problem.

**Comment by kidzgy** [comment]
[violentmonkey_2023-02-11_09.51.35.zip](https://github.com/violentmonkey/violentmonkey/files/10712328/violentmonkey_2023-02-11_09.51.35.zip)

**Comment by tophf** [comment]
It didn't help because the backup doesn't contain the temporary data from the internal database. Please share the portable Firefox again or at least its `profile` directory.

**Comment by kidzgy** [comment]
https://wwi.lanzoup.com/iaLK50n9c7mj

**Comment by tophf** [comment]
Thanks. Should be fixed in [this build](https://github.com/violentmonkey/violentmonkey/suites/10919973819/artifacts/552005395).

**Comment by fullmetal1** [comment]
Latest build works for me. Thanks

**Comment by kidzgy** [comment]
Tried it out and feel like there's really no problem this time. Thanks for the effort to keep trying to fix the bugs!

**Comment by kidzgy** [comment]
I found another bug that every time I open the page settings under the script, two pages will pop up, which is equivalent to clicking twice.
![2023-02-12_204407](https://user-images.githubusercontent.com/6967810/218311855-fe74ed4b-f378-41aa-99dd-2704803a203b.png)

**Comment by tophf** [comment]
I guess it's a bug in these scripts: if they run inside iframes they should check `window==top` and not show their settings.

**Comment by kidzgy** [comment]
I installed back to version 2.13.3 and no problem. I reinstalled this latest version 2.13.9.2 and the problem did not recur. Very strange!
I'll see if I encounter the problem again in the future and try to describe the steps to reproduce it.

**Comment by tophf** [comment]
It's not strange. New Violentmonkey notifies all running scripts when the menu button is clicked, including those inside iframes.

**Comment by tophf** [comment]
However, if the site doesn't have any iframes then it may be a bug. In that case please open a new report.

**Comment by kidzgy** [comment]
![2023-02-13_004619](https://user-images.githubusercontent.com/6967810/218324831-62f9a719-ae33-4664-a85a-ed7a77b1ce46.png)
Although I did not encounter the bug that the script was not loaded successfully even though it was clearly displayed.
But now we encounter a new bug that none of the scripts in the script list can be displayed. This bug recurs very randomly, the probability of appearing is smaller than the previous bug, and there is no error message in the console.

The link I tested is https://www.baidu.com/s?wd=1&rn=20, and there is a probability that the bug will recur if I keep refreshing the page.

**Comment by tophf** [comment]
I can't reproduce it and the site redirects me to a captcha verification after a few refreshes.

**Comment by tophf** [comment]
Check the background log of Violentmonkey in `about:debugging`:

![image](https://user-images.githubusercontent.com/1310400/218325491-a74cc860-a6c3-4d73-a012-bddf2bf688ce.png)

**Comment by tophf** [comment]
Also try disabling "Alternative page mode in Firefox" in [the new build](https://github.com/violentmonkey/violentmonkey/suites/10931034576/artifacts/552811748).

**Comment by kidzgy** [comment]
I have used the above version and have turned off the option "Alternative page mode in Firefox", but I still have the same problem.
![微信截图_20230213201840](https://user-images.githubusercontent.com/6967810/218456106-f9bc9d96-5ea3-428d-89fe-b761f5bcac96.png)

**Comment by tophf** [comment]
1. Did you try [this one](https://github.com/violentmonkey/violentmonkey/actions/runs/4163111947)?
2. Do the scripts actually run in the page when this happens?

**Comment by kidzgy** [comment]
> 1. Did you try [this one](https://github.com/violentmonkey/violentmonkey/actions/runs/4163111947)?
> 
>     2. Do the scripts actually run in the page when this happens?

1.Yes, I just tried this file and still have the same problem.
2.The list doesn't show any scripts, and none of them are actually loaded.

**Comment by tophf** [comment]
Well, I don't know how it can happen even conceptually, so I can't fix it.

**Comment by kidzgy** [comment]
It is very strange that I have not been able to reproduce this bug on sites other than Baidu.
Also, I noticed that the Baidu search page shows some errors about VMs in the console when the script can be successfully loaded. The details are as follows.
![微信截图_20230213205330](https://user-images.githubusercontent.com/6967810/218463792-ed96a392-057f-4406-8ab0-4112410b9a1a.png)
![微信截图_20230213205308](https://user-images.githubusercontent.com/6967810/218463800-14db4190-0499-4144-97ae-07bc923b275c.png)

**Comment by tophf** [comment]
That error is caused by your `SciHub CRX` script.

**Comment by tophf** [comment]
I've fixed this error, try the [new build](https://github.com/violentmonkey/violentmonkey/actions/runs/4163889165).

**Comment by kidzgy** [comment]
The console does not have that error anymore.
However, the bug with the script not loading was not fixed and I did not enable the SciHub CRX script this time.
The bug was too hard to reproduce.Forget it.
![微信截图_20230213212938](https://user-images.githubusercontent.com/6967810/218473451-806a8d03-2856-454e-8084-c09472447602.png)

**Comment by kidzgy** [comment]
I was using version 2.13.3 but came out with no such problem.

**Comment by tophf** [comment]
It's possible that something in our new code is triggering the bug in Firefox, but I don't know what.

Here's a modified test build that prints the warning in the [background console](https://github.com/violentmonkey/violentmonkey/issues/1739#issuecomment-1427082127).

[Violentmonkey-test-srctab-warning.zip](https://github.com/violentmonkey/violentmonkey/files/10723105/Violentmonkey-test-srctab-warning.zip)

![image](https://user-images.githubusercontent.com/1310400/218483678-90b49505-f83d-4390-b5ea-482ca80f7d80.png)

**Comment by tophf** [comment]
Another explanation may be that 2.13.3 was slower, so it didn't "notice" the bug in Firefox.

**Comment by kidzgy** [comment]
I don't know why, but the error message in the VM console sometimes shows "NO SRC.TAB..."
![微信截图_20230213230709](https://user-images.githubusercontent.com/6967810/218495611-606a46d7-68b3-4eb4-8051-c1a0404c21cc.png)
![微信截图_20230213225700](https://user-images.githubusercontent.com/6967810/218495627-18d12eff-47af-4ec2-ab9f-9a5a00027756.png)

**Comment by kidzgy** [comment]
If it is a Firefox bug, can you please report this bug to the official?

**Comment by tophf** [comment]
I don't report bugs that I can't reproduce myself, but I can report it if you find something in mozregression (see my comment above).

**Comment by kidzgy** [comment]
![微信截图_20230214002443](https://user-images.githubusercontent.com/6967810/218514212-09f5af92-603a-4d97-9d24-538e4c082923.png)
I don't know what this warning means.

**Comment by tophf** [comment]
It's shown because we use the same manifest.json in Chrome and Firefox, so the unsupported parts are ignored by the browser, this is what the warning says. It doesn't have any bearing on the bug you observe.

**Comment by kidzgy** [comment]
I have an idea, the "rare injection error in Firefox" bug first started to appear in 2.13.3.8, is it possible to fix the bug in this version?
If the problem I encountered above is reproduced in the 2.13.3.8 version with the bug fixed, then I can compare which code is the problem.

**Comment by tophf** [comment]
I've reviewed the changes between 2.13.3.7 and 2.13.3.8 several times and I didn't see how any of them can cause this bug. Thing is, the lack of `src.tab` in a message is not something that we can influence. It's something that Firefox must put there.

Can you verify again that 2.13.3.7 is fine and 2.13.3.8 is not?

**Comment by kidzgy** [comment]
![2023-02-14_004822](https://user-images.githubusercontent.com/6967810/218520015-c8832ac7-5eda-4bb4-b6fd-f738dc90cdb2.png)
I have tried many times, 2.13.3.7 is no problem, the problem is 2.13.3.8.

**Comment by tophf** [comment]
Well, then we will have to wait for someone to debug it.

**Comment by tophf** [comment]
Wow, I'm seeing it now using your bookmarks, so there's a chance I'll be able to find a workaround.

**Comment by tophf** [comment]
Yay, I found a mistake in our code.

**Comment by tophf** [comment]
Fixed build: [zip](https://github.com/violentmonkey/violentmonkey/suites/10954760174/artifacts/554464550)

**Comment by tophf** [comment]
@kidzgy, did you test it already? I want to publish a new beta.

**Comment by kidzgy** [comment]
I tested it, no problems for now, it's perfect!
