### ISSUE TITLE
[BUG] GM_xmlHttpRequest should send passed in cookies even when `anonymous` is true?

### ISSUE THREAD

**Issue by lyc8503** [violentmonkey/violentmonkey#1848]
### Sequence of actions: 
Write the code below in violentmonkey
```
GM_xmlhttpRequest({
    method: "GET",
    url: "https://www.example.com/",
    anonymous: true,
    headers: {
        "Cookie": "MY_COOKIE=1;"
    }
})
```

### Problem: 
The request sent didn't have `Cookie: MY_COOKIE=1;` in its headers

### Expected result:  
I thought the explicit passed-in cookies should be sent with the request even `anonymous` is set to true. (which is the case for Tampermonkey in my test)

In my use case, I want to override its original cookies on `example.com`, if I set `anonymous` to false, the original cookies will be sent together with my passed-in cookies, which can cause problems.

A developer should always be in control of the arguments passed to `GM_xmlhttpRequest`, so when an explicit `Cookie` field is passed to `GM_xmlhttpRequest`, the developer expect it to be sent with the request.

#### Devtools console contents:
Nothing here

#### Environment:
- OS: Windows
- Browser: Chrome 114
- Violentmonkey Version: 2.14.0

**Comment by tophf** [comment]
I think it's fixed in [f332f55e](https://github.com/violentmonkey/violentmonkey/suites/14173249232/artifacts/794509207), could you try it by loading as an unpacked extension?

**Comment by lyc8503** [comment]
> I think it's fixed in [f332f55e](https://github.com/violentmonkey/violentmonkey/suites/14173249232/artifacts/794509207), could you try it by loading as an unpacked extension?

I tested on my Edge 114 this time, but it seems that the problem is still not fixed?

The full code I used to test and the request screenshot is as below. There‘s no `Cookies` header.

```
// ==UserScript==
// @name        New script - extensions
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      -
// @grant       GM_xmlhttpRequest
// @description 2023/7/10 16:23:17
// ==/UserScript==

GM_xmlhttpRequest({
    method: "GET",
    url: "https://www.example.com/",
    anonymous: true,
    headers: {
        "Cookie": "MY_COOKIE=1;"
    }
})

```


![image](https://github.com/violentmonkey/violentmonkey/assets/36782264/f1a1e5bc-76be-4508-81e5-3cfd5ce75f16)

**Comment by cyber-sec0** [comment]
@tophf 
The issue with the rewatched script I mentioned earlier still happening

https://myanimelist.net/forum/?topicid=1855693&msgid=69360605#msg69360605

**Comment by lyc8503** [comment]
@tophf 
I spotted another weird behavior with this API.
It now works well on `example.com` / Twitter, but didn't send `Cookie` headers to Google/Youtube on my browser.
But the same script can work in Tampermonkey to send `MY_COOKIE` to Google, what could be the cause here?

```
GM_xmlhttpRequest({
    method: "GET",
    url: "https://www.google.com/",
    anonymous: true,
    headers: {
        "Cookie": "MY_COOKIE=1;"
    }
})
```

**Comment by tophf** [comment]
@cyber-sec0, which issue exactly? There's a lot of text in the link you gave. I opened #1835 for you and it's fixed for me now.
@lyc8503, indeed, our code is still incorrect when the site has existing cookies, fixed in 6ae569d4, please test.

**Comment by tophf** [comment]
The fixed build: https://github.com/violentmonkey/violentmonkey/suites/14263589826/artifacts/801443076

**Comment by lyc8503** [comment]
> @cyber-sec0, which issue exactly? There's a lot of text in the link you gave. I opened #1835 for you and it's fixed for me now. @lyc8503, indeed, our code is still incorrect when the site has existing cookies, please test [the fixed build](https://github.com/violentmonkey/violentmonkey/suites/14263589826/artifacts/801443076).

It works now on my own script, Thanks!
