### ISSUE TITLE
[BUG] v2.15.1 BETA `GM_xmlhttpRequest` cannot correctly handle links for secondary jumps.

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#1865]
### Sequence of actions: 
Please clear browser cache to reproduce this issue.

For example: get data from following link https://www.baidu.com/link?url=85O0XYarP941o--EFlRHHOLfKhbRhzBk0uJddg7eg8n4fGw_Nt0UZIujQsAEA3K-&wd=&eqid=a6d571320000961d0000000664d317da

It is normal in v2.15.0, but the real data cannot be obtained in v2.15.1 BETA.

#### Environment:
- OS: Win10 
- Browser: Chrome 115
- Violentmonkey Version: v2.15.1 BETA

**Comment by tophf** [comment]
I have no idea how to test this. Please add a userscript and an instruction.

**Comment by tophf** [comment]
Also try the [latest build](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml) which fixed a bug that sounds similar to what you described.

**Comment by F9y4ng** [comment]
In the following code of my script, https://github.com/F9y4ng/GreasyFork-Scripts/blob/44296798656417fc2e5ce678a785b3236e01c800/Google%20%26%20Baidu%20Switcher.user.js#L1125-L1127

```js
onreadystatechangeFunc: resolve => response => {
  if (response.status === 200 && response.readyState === 4) resolve(response.finalUrl || response.responseURL);
},
```

In v2.15.1 BETA, when `response.readyState === 4` can't get the value of `response.finalUrl`, the code only executes to `readyState: 3` and then ends.

![err](https://github.com/violentmonkey/violentmonkey/assets/15855068/9485f2e7-126e-45e4-adce-0a833f31d7c9)

**The above code is normal in v2.15.0.**

**Comment by tophf** [comment]
Yeah, it should be fixed in the latest build I've linked above.

**Comment by tophf** [comment]
Ah no, it's a different bug, I'll look into it.

**Comment by tophf** [comment]
Should be fixed in the [latest build](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml), please test it and I'll release the new beta.

**Comment by F9y4ng** [comment]
> Should be fixed in the [latest build](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml), please test it and I'll release the new beta.

No, the lastest build did not fix this problem.
![err1](https://github.com/violentmonkey/violentmonkey/assets/15855068/b8369c07-1393-4ff9-bd35-1374a741a24b)

**Comment by tophf** [comment]
Try the newest build please.
