### ISSUE TITLE
ViolentMonkey icon indicates "1" but no userscripts are loaded

### ISSUE THREAD

**Issue by dartraiden** [violentmonkey/violentmonkey#501]
How to reproduce:
- Firefox 64.0.2, ViolentMonkey 2.10.1
- install https://greasyfork.org/ru/scripts/39639-unembed-gleam-giveaways
- set Default injection mode to auto
- go to https://www.idropnews.com/giveaways/apple-iphone-xr-giveaway/88322/

Expected result:
https://i.imgur.com/tjw103x.png

Actual result: no icon in top right corner. ViolentMonkey icon indicates "1" but no userscripts are loaded

![firefox_yqrqbd8dmm](https://user-images.githubusercontent.com/5046855/51445977-6b6b6180-1d1c-11e9-9a6e-cfbe1a8c7a53.png)

**Comment by CCStreamZ** [comment]
Did you find a solution to this on violentmonkey?

**Comment by tophf** [comment]
It's an old version of Violentmonkey so this bug probably is already fixed in the [new beta](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by CCStreamZ** [comment]
I tried it with the same script in the latest Violentmonkey and in the Violentmonkey Beta and it still doesn't work. I tried in Tampermonkey and it works fine. It'd be great if they fixed this, I prefer Violentmonkey.

**Comment by tophf** [comment]
I can't replicate the problem here using the instruction in the issue description, so there's nothing we can do about it.
